#!/bin/bash
# Install Minecraft Java Forge server on Raspberry Pi OS 64-bit.
# Usage:
#   chmod +x install_minecraft_forge_rpi.sh
#   sudo ./install_minecraft_forge_rpi.sh
# Optional env vars:
#   MC_VERSION=1.20.1 FORGE_VERSION=47.3.0 SERVER_PORT=25565 ./install_minecraft_forge_rpi.sh

set -euo pipefail

MC_VERSION="${MC_VERSION:-26.1.2}"
FORGE_VERSION="${FORGE_VERSION:-64.0.4}"
SERVER_PORT="${SERVER_PORT:-25565}"
SERVER_USER="${SERVER_USER:-minecraft}"
INSTALL_DIR="${INSTALL_DIR:-/opt/minecraft-forge}"
BACKUP_DIR="${BACKUP_DIR:-/var/backups/minecraft-forge}"

FORGE_FULL_VERSION="${MC_VERSION}-${FORGE_VERSION}"
FORGE_INSTALLER="forge-${FORGE_FULL_VERSION}-installer.jar"
FORGE_URL="https://maven.minecraftforge.net/net/minecraftforge/forge/${FORGE_FULL_VERSION}/${FORGE_INSTALLER}"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

if [ "${EUID}" -ne 0 ]; then
  echo -e "${RED}Run this installer as root (sudo).${NC}"
  exit 1
fi

echo -e "${BLUE}== Minecraft Forge Server Installer (Raspberry Pi) ==${NC}"
echo "MC version: ${MC_VERSION}"
echo "Forge version: ${FORGE_VERSION}"
echo "Install dir: ${INSTALL_DIR}"
echo

if ! grep -q "Raspberry Pi" /proc/device-tree/model 2>/dev/null; then
  echo -e "${YELLOW}Warning: This host does not look like a Raspberry Pi.${NC}"
fi

# Forge 64.x requires Java 25. Keep fallbacks for older Forge lines.
echo -e "${GREEN}[1/8] Installing base packages...${NC}"
apt-get update

JAVA_PACKAGE=""
if apt-cache show openjdk-25-jre-headless >/dev/null 2>&1; then
  JAVA_PACKAGE="openjdk-25-jre-headless"
elif apt-cache show openjdk-21-jre-headless >/dev/null 2>&1; then
  JAVA_PACKAGE="openjdk-21-jre-headless"
elif apt-cache show openjdk-17-jre-headless >/dev/null 2>&1; then
  JAVA_PACKAGE="openjdk-17-jre-headless"
else
  echo -e "${RED}No compatible OpenJDK package found (25, 21 or 17).${NC}"
  exit 1
fi

apt-get install -y "${JAVA_PACKAGE}" curl ca-certificates tar ufw

echo -e "${GREEN}[2/8] Creating minecraft user and folders...${NC}"
if ! id -u "${SERVER_USER}" >/dev/null 2>&1; then
  useradd -r -m -d /home/${SERVER_USER} -s /usr/sbin/nologin "${SERVER_USER}"
fi

mkdir -p "${INSTALL_DIR}" "${BACKUP_DIR}"
chown -R "${SERVER_USER}:${SERVER_USER}" "${INSTALL_DIR}" "${BACKUP_DIR}"

echo -e "${GREEN}[3/8] Downloading Forge installer...${NC}"
rm -f "${INSTALL_DIR}/${FORGE_INSTALLER}"
sudo -u "${SERVER_USER}" bash -lc "cd '${INSTALL_DIR}' && curl -fL '${FORGE_URL}' -o '${FORGE_INSTALLER}'"

echo -e "${GREEN}[4/8] Installing Forge server files...${NC}"
sudo -u "${SERVER_USER}" bash -lc "cd '${INSTALL_DIR}' && java -jar '${FORGE_INSTALLER}' --installServer"

# Accept EULA for non-interactive setup.
echo -e "${GREEN}[5/8] Writing server configs...${NC}"
cat > "${INSTALL_DIR}/eula.txt" <<EOF
# Auto-generated by install script
eula=true
EOF

if [ ! -f "${INSTALL_DIR}/server.properties" ]; then
  sudo -u "${SERVER_USER}" bash -lc "cd '${INSTALL_DIR}' && touch server.properties"
fi

set_prop() {
  local key="$1"
  local value="$2"
  if grep -q "^${key}=" "${INSTALL_DIR}/server.properties"; then
    sed -i "s|^${key}=.*|${key}=${value}|" "${INSTALL_DIR}/server.properties"
  else
    echo "${key}=${value}" >> "${INSTALL_DIR}/server.properties"
  fi
}

set_prop "motd" "Minecraft Forge on Raspberry Pi"
set_prop "server-port" "${SERVER_PORT}"
set_prop "online-mode" "true"
set_prop "enable-command-block" "false"
set_prop "white-list" "true"
set_prop "max-players" "8"
set_prop "view-distance" "8"
set_prop "simulation-distance" "6"
set_prop "spawn-protection" "0"

TOTAL_MB="$(awk '/MemTotal/ { print int($2/1024) }' /proc/meminfo)"
if [ "${TOTAL_MB}" -ge 7000 ]; then
  XMX="4096M"
elif [ "${TOTAL_MB}" -ge 3800 ]; then
  XMX="2560M"
else
  XMX="1536M"
fi

cat > "${INSTALL_DIR}/user_jvm_args.txt" <<EOF
-Xms1024M
-Xmx${XMX}
-XX:+UseG1GC
-XX:MaxGCPauseMillis=200
EOF

mkdir -p "${INSTALL_DIR}/mods" "${INSTALL_DIR}/config"
chown -R "${SERVER_USER}:${SERVER_USER}" "${INSTALL_DIR}"

echo -e "${GREEN}[6/8] Installing start and backup scripts...${NC}"
cat > /usr/local/bin/start-minecraft-forge.sh <<EOF
#!/bin/bash
set -euo pipefail
cd "${INSTALL_DIR}"
if [ ! -x ./run.sh ]; then
  echo "run.sh not found or not executable in ${INSTALL_DIR}" >&2
  exit 1
fi
exec ./run.sh nogui
EOF
chmod +x /usr/local/bin/start-minecraft-forge.sh

cat > /usr/local/bin/backup-minecraft-forge.sh <<EOF
#!/bin/bash
set -euo pipefail
STAMP=\"\$(date +%Y%m%d-%H%M%S)\"
DEST="${BACKUP_DIR}/minecraft-world-\${STAMP}.tar.gz"
cd "${INSTALL_DIR}"
if [ -d world ]; then
  tar -czf "\${DEST}" world world_nether world_the_end whitelist.json ops.json server.properties eula.txt 2>/dev/null || true
  find "${BACKUP_DIR}" -type f -name '*.tar.gz' -mtime +7 -delete
  echo "Backup created at: \${DEST}"
else
  echo "No world directory yet. Start the server once first."
fi
EOF
chmod +x /usr/local/bin/backup-minecraft-forge.sh

echo -e "${GREEN}[7/8] Installing systemd service...${NC}"
cat > /etc/systemd/system/minecraft-forge.service <<EOF
[Unit]
Description=Minecraft Forge Server
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${SERVER_USER}
WorkingDirectory=${INSTALL_DIR}
ExecStart=/usr/local/bin/start-minecraft-forge.sh
Restart=always
RestartSec=10
SuccessExitStatus=0 1
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable minecraft-forge.service

echo -e "${GREEN}[8/8] Opening firewall port ${SERVER_PORT}/tcp (ufw)...${NC}"
if command -v ufw >/dev/null 2>&1; then
  ufw allow ${SERVER_PORT}/tcp >/dev/null 2>&1 || true
fi

echo
echo -e "${GREEN}Installation finished.${NC}"
echo "Next commands:"
echo "  sudo systemctl start minecraft-forge"
echo "  sudo systemctl status minecraft-forge"
echo "  sudo journalctl -u minecraft-forge -f"
echo "  Use in-game: /whitelist add <player>"
echo ""
echo "Mods folder: ${INSTALL_DIR}/mods"
echo "Backup script: /usr/local/bin/backup-minecraft-forge.sh"
