#!/bin/bash
# Quick start guide for Kingshot Bot on Raspberry Pi

echo "================================"
echo "Kingshot Bot - Quick Start"
echo "================================"
echo ""
echo "Step 1: Initial Setup"
echo "  1.1 Copy .env.example to .env"
echo "       cp .env.example .env"
echo ""
echo "  1.2 Edit .env with your Discord token"
echo "       nano .env"
echo ""
echo "Step 2: Install Dependencies"
echo "  2.1 Create virtual environment (recommended)"
echo "       python3 -m venv venv"
echo "       source venv/bin/activate"
echo ""
echo "  2.2 Install Python packages"
echo "       pip install -r requirements.txt"
echo ""
echo "Step 3: Run the Bot"
echo "  Option A - Manual Start:"
echo "       python main.py"
echo ""
echo "  Option B - As a service (24/7):"
echo "       sudo cp kingshot-bot.service /etc/systemd/system/"
echo "       sudo systemctl daemon-reload"
echo "       sudo systemctl enable kingshot-bot"
echo "       sudo systemctl start kingshot-bot"
echo ""
echo "Step 4: Verify it's working"
echo "  - Go to Discord and type: /help"
echo "  - Bot should respond with help message"
echo ""
echo "Step 5: Check logs (if running as service)"
echo "  journalctl -u kingshot-bot -f"
echo ""
echo "================================"
echo "For more info, see README.md"
echo "================================"
