"""
Properties for Auto Rigger addon
Defines custom properties for rig configuration and settings.
"""

import bpy
from bpy.props import (
    StringProperty,
    EnumProperty,
    BoolProperty,
    FloatProperty,
    PointerProperty,
    IntProperty,
)
from bpy.types import PropertyGroup


class AutoRigSettings(PropertyGroup):
    """Settings for automatic rigging"""
    
    # Target mesh selection
    target_mesh: PointerProperty(
        name="Target Mesh",
        description="The mesh object to rig",
        type=bpy.types.Object,
        poll=lambda self, obj: obj.type == 'MESH'
    )
    
    # Body type preset
    body_type: EnumProperty(
        name="Body Type",
        description="Character body type for proportions",
        items=[
            ('MALE', "Male", "Adult male proportions"),
            ('FEMALE', "Female", "Adult female proportions"),
            ('CHILD', "Child", "Child proportions (larger head ratio)"),
            ('STYLIZED', "Stylized", "Cartoon/anime proportions"),
            ('CUSTOM', "Custom", "Use custom detection"),
        ],
        default='MALE'
    )
    
    # Bone naming convention
    bone_naming: EnumProperty(
        name="Naming Convention",
        description="Bone naming standard to use",
        items=[
            ('MIXAMO', "Mixamo", "Mixamo standard (most universal)"),
            ('UNREAL', "Unreal Engine", "Unreal Engine naming"),
            ('UNITY', "Unity/Mecanim", "Unity Mecanim humanoid"),
            ('RIGIFY', "Rigify", "Blender Rigify naming"),
        ],
        default='MIXAMO'
    )
    
    # Rig complexity
    rig_type: EnumProperty(
        name="Rig Type",
        description="Complexity of the generated rig",
        items=[
            ('BASIC', "Basic", "Simple FK skeleton only"),
            ('STANDARD', "Standard", "IK/FK for limbs with controls"),
            ('ADVANCED', "Advanced", "Full control rig with fingers"),
        ],
        default='STANDARD'
    )

    # Rig source
    rig_source: EnumProperty(
        name="Rig Source",
        description="Choose the rig layout source",
        items=[
            ('AUTO', "Auto Rigger", "Use automatic layout generated by this addon"),
            ('RIGIFY_HUMAN', "Blender Human (Rigify)", "Use Blender Rigify human meta-rig layout"),
        ],
        default='AUTO'
    )

    rigify_generate_controls: BoolProperty(
        name="Generate Rigify Controls",
        description="Generate Rigify control rig after fitting the human meta-rig",
        default=False
    )
    
    # Weight painting method
    weight_method: EnumProperty(
        name="Weight Method",
        description="Method for automatic weight painting",
        items=[
            ('HEAT', "Heat Diffusion", "Better quality, slower (recommended)"),
            ('AUTOMATIC', "Automatic", "Blender automatic weights"),
            ('DISTANCE', "Distance Based", "Simple distance calculation, faster"),
            ('ENVELOPE', "Envelope", "Bone envelope based"),
        ],
        default='HEAT'
    )
    
    # Advanced options
    detect_symmetry: BoolProperty(
        name="Detect Symmetry",
        description="Automatically detect and use mesh symmetry",
        default=True
    )
    
    symmetry_tolerance: FloatProperty(
        name="Symmetry Tolerance",
        description="Tolerance for symmetry detection",
        default=0.001,
        min=0.0001,
        max=0.1,
        precision=4,
    )
    
    create_ik: BoolProperty(
        name="Create IK Controls",
        description="Generate IK controls for arms and legs",
        default=True
    )
    
    create_pole_targets: BoolProperty(
        name="Create Pole Targets",
        description="Create pole targets for IK chains",
        default=True
    )
    
    add_finger_bones: BoolProperty(
        name="Add Fingers",
        description="Add finger bones (if advanced rig)",
        default=False
    )
    
    add_twist_bones: BoolProperty(
        name="Add Twist Bones",
        description="Add twist bones for forearm and shin",
        default=False
    )
    
    spine_bones: IntProperty(
        name="Spine Bones",
        description="Number of spine bones",
        default=3,
        min=1,
        max=6
    )
    
    # Quality and validation
    validate_weights: BoolProperty(
        name="Validate Weights",
        description="Check weight quality and highlight issues",
        default=True
    )
    
    smooth_weights: BoolProperty(
        name="Smooth Weights",
        description="Apply smoothing to weight transitions",
        default=True
    )
    
    smooth_iterations: IntProperty(
        name="Smooth Iterations",
        description="Number of smoothing passes",
        default=3,
        min=0,
        max=10
    )
    
    # Generation options
    preserve_original: BoolProperty(
        name="Preserve Original",
        description="Keep original mesh unchanged (duplicate for rigging)",
        default=True
    )
    
    auto_generate_poses: BoolProperty(
        name="Generate Poses",
        description="Automatically create T-pose and A-pose",
        default=True
    )
    
    # Internal state (not shown in UI)
    landmarks_detected: BoolProperty(
        name="Landmarks Detected",
        description="Whether body landmarks have been detected",
        default=False
    )
    
    generation_progress: FloatProperty(
        name="Progress",
        description="Generation progress percentage",
        default=0.0,
        min=0.0,
        max=100.0,
        subtype='PERCENTAGE'
    )
